### PR TITLE
get_volume.py; Calc. volume by rotating contour

### PR DESCRIPTION
**Pull request by maikherbig**
The volume of objetcs can be determined by rotating the contour. Volume has the advantage to be less correlated to deformation compared to the projected area and is therefore a better measure of 'cell size' in the channel.

### CODE REVIEW

**Comment by paulmueller** [comment]
Thanks for the pull request.

Please address the following points.
- Please move the tests to a separate test file in the tests directory.
- Please rename get_volume.py to volume.py.
- Please make sure the method "get_volume" works for float and ndarrays by using e.g. `np.atleast_1d(pos_x)`
- Initiate v_avg as an array, e.g. `v_avg = np.zeros_like(pos_x,dtype=float)*np.nan`
- The comments are confusing regarding what is shifted up and down. please check.
- In the docstring, stae that `mm` is an instance of `RTDC_DataSet`
- It looks like the computation of the upper and lower volumes use exactly the same code - this could be moved to a separate method.
- Please catch all specific errors that you anticipate in the `except:` statement. e.g. `except ValueError` and state why and where you would expect it.

**Comment by MaikH88** [comment]
Could this function be used similarly to "get_elasticity" to calculate volume on in ShapeOut in the "Calculate" tab?

**Comment by paulmueller** [comment]
Yes, this could be added to ShapeOut.

Regarding the except statement:
You commented:

     If the contour has less than 4 pixels, the computation will fail

I suggest checking for the length of the contour instead of using try-except here.
If an exception can be avoided, there is no need to make the code more difficult to debug.

**Comment by maikherbig** [comment]
Hmm, I am not 100% sure if that is the only case that it could fail. Therefore I would prefer to leave try and  except.

**Comment by paulmueller** [comment]
Sorry, if you are not 100% sure, then I am not willing to merge your code.
In my opinion, it is not an option to leave the try-except statement. If you are not 100% certain, you should write test methods to improve confidence.

**Comment by paulmueller** [comment]
I am merging into a separate branch for testing.

**Pull request merged**
