### PR TITLE
Compute Inertia Ratio

### PR DESCRIPTION
**Pull request by maikherbig**
Inertia Ratio is recorded online in newer versions of ShapeIn. This property can also be obtained offline from the contours. Inertia Ratio is closely liked to "Deformation"  (=1-circulrity), but has the advantage to be less affected by protrusions and non-convex shapes. In future it might also be used to look up E-Modulus using an appropriate LUT.

### CODE REVIEW

**Comment by maikherbig** [comment]
Like in this pull request:
https://github.com/ZELLMECHANIK-DRESDEN/dclab/pull/19
I wrote a test-function that computes the Inertia Ratio from the contours and compares it to the values obtained online (during a measurement). One can use again the "testdataset" uploaded to the aforementioned pull request.
[inertiaratio_1.zip](https://github.com/ZELLMECHANIK-DRESDEN/dclab/files/1073642/inertiaratio_1.zip)

**Comment by paulmueller** [comment]
Thanks for the pull request. Could you please add (or link to) a definition of inertia ratio (and why it is more advantageous).

**Comment by maikherbig** [comment]
Inertia Ratio (I) is calculated using the second moment of area (or "moment-of-area tensor") and was defined here (they call it "Λ1/Λ2"):
http://pubs.acs.org/doi/abs/10.1021/acsbiomaterials.6b00558
It is a useful measure for Deformation because:
-It can be computed on the original contour (does not need a convex hull like circularity)
-Strong correlation to Deformation (1-circularity)
-Low correlation to area ratio
I have computed the correlations using >1800 different experiments:
correlations

**Comment by paulmueller** [comment]
I would like to get rid of the `cv2` dependence in dclab, because `cv2` is not on pypi and it makes testing very painful. Computation of moments is also possible with scipy.

**Comment by maikherbig** [comment]
There is a page on pypi for OpenCV:
https://pypi.python.org/pypi/opencv-python
and one can install it using "pip install opencv-python"
Does this change your mind?

**Comment by paulmueller** [comment]
No, because:
```
IMPORTANT NOTE

MacOS and Linux wheels have currently some limitations:

    video related functionality is not supported (not compiled with FFmpeg)
    for example cv2.imshow() will not work (not compiled with GTK+ 2.x or Carbon support)
```

**Comment by maikherbig** [comment]
Hmm thats a pity. This problem seems to be not present in a older version:
https://pypi.python.org/pypi/opencv-python/3.1.0.3

**Comment by maikherbig** [comment]
Inerita Ratio has no rotational invariance, which is especially a problem, if we want to use it for reservoir measurements. Rotational invariance is no problem in the channel since cells are aligned by the flow anyway, but  the slow flow in the reservoir is not able to align all cells. The principal seond moment of area has rotational invariance. To compute it, the contour is rotated such that the second moment is maximal in x direction and minimal in y-direction.
The following histogram shows one example measurement in the channel. It shows that Inertia Ratio and Principal inertia ratio are very similar, since the channel does already align the cells:
ir_vs_princir_channel


On the other hand, in the reservoir, the cells are not so well aligned, which causes that the Principal Inertia Ratio is larger than the Inertia Ratio:
ir_vs_princir_reservoir

**Comment by paulmueller** [comment]
Should be compute the principal inertia ratio by default or add a new column for it?

**Comment by maikherbig** [comment]
A new column should be added. Maybe this new property can in future also be computed online (in addition).

**Comment by paulmueller** [comment]
FYI: Currently, other issues in dclab/ShapeOut have higher priority than inertia ratio, delaying this pull request.

**Comment by paulmueller** [comment]
There is quite a list of moments in skimage.measure, e.g. [Hu moments](http://scikit-image.org/docs/dev/api/skimage.measure.html#moments-hu), which are translation, scale and rotation invariant.

**Comment by maikherbig** [comment]
I have a small "testdataset" where we already obtained interia ratio online unsing OpenCV. I wrote a script that load this measurement, and computes the interia ratio newly from the contours using:
-OpenCV
-SciPy Moments
-Skimage Moments
-Algorithm from wikipedia (https://en.wikipedia.org/wiki/Second_moment_of_area)
Then it compares for each cell the inertia ratio determined online and by the respective algorithm.

Output of the script:
Use OpenCV:
Error is = 1.65033817038e-06
------------------------------
Use SciPy:
Error is = 11.0561887963
------------------------------
Use Algorithm from Wikipedia:
Error is = 5.35437688617
------------------------------
Use Own Skimage:
Error is = 3.73017674717
------------------------------

Apparently, only using OpenCV I can reproduce the inertia ration determined online.

**Comment by paulmueller** [comment]
It turns out that translating the OpenCV moment computation into a vectorized numpy method is straight forward. There is now an ancillary column for `inert_ratio_raw`. I will test `inert_ratio_cvx` too.
References:
- https://github.com/ZELLMECHANIK-DRESDEN/dclab/commit/4924d8813aade6f797c9b5d17c94369d665f5173
- https://github.com/opencv/opencv/blob/26be2402a3ad6c9eacf7ba7ab2dfb111206fffbb/modules/imgproc/src/moments.cpp

**Comment by paulmueller** [comment]
`inert_ratio_cvx` works as well: https://github.com/ZELLMECHANIK-DRESDEN/dclab/commit/57de14cb1c12c5486baf372be2c6c7d35b2143e2

I would like to wait for feedback from @chrherold and @phidahl regarding the principal inertia ratio problem.

**Comment by chrherold** [comment]
I think it makes sense to add a new column for the principal inertia ratio that is available in expert mode. With that, tests for its usefulness can be performed by the people interested in it.
If usefulness is established by publication, we can move it to the normal use and calculate it also directly in ShapeIn.

It should be done on the raw contour. I do not see the point of doing it on the convex hull, but maybe @maikherbig disagrees. In this case adding two columns could be one.

**Comment by maikherbig** [comment]
I would also agree that principal inertia ratio should be accessible for users. It will be useful for channel measurements that are recorded with tilted camera view. For sensible use of Inertia Ratio, the channel should be straight. Also in the reservoir, prinicipal inertia ratio should be used since cells are not aligned by the flow there. Inertia Ratio and Principal Inertia Ratio can and should be computed on the raw contour. The only reason, we compute it for the raw contour and the convex hull is becasue the additional computational cost during acquisition (online evaluation during measurement) is negligible and we were not sure if someone might has an idea what it could be good for. Probably there is no need for (Principal) Inertia Ratio on the convex hull. I'm currently calculating the Inertia Ratio and Principal inertia ratio for thousands of experiments. If you want we can discuss how this data could be used to prove usefulness or unusefulness of Inertia Ratio and Principal Inertia Ratio.

**Comment by paulmueller** [comment]
I am closing this pull request because it is based on an old tree and will probably not merge correctly. I created a separate issue for the principal inertia ratio: +46

**Pull request closed without merging**
