### PR TITLE
Calc. mean and std brightness inside contour

### PR DESCRIPTION
**Pull request by maikherbig**
Grayscale values of the images and the contours can be used to determine the brightness and the std. of the brightness (offline):
https://github.com/ZELLMECHANIK-DRESDEN/dclab/issues/18

### CODE REVIEW

**Comment by maikherbig** [comment]
Hi Paul,
the main function to determin brightness is there now but a test is missing that it works in the same way like ShapeIn. Therefore I'd like to send you a "testdataset", which is a more recent RT-DC measurement with Brightness. The attached script loads the measurement. To get the images I'm using here imageio, which might solve this issue: https://github.com/ZELLMECHANIK-DRESDEN/ShapeOut/issues/129.
Then I compare the Brightness values determined online with the brightness values obtained using get_brightness(). I thought this is reasonable testfunction.
Best,
Maik
[For_Paul_20170613.zip](https://github.com/ZELLMECHANIK-DRESDEN/dclab/files/1072827/For_Paul_20170613.zip)

**Comment by paulmueller** [comment]
Thanks for the input. I will have a look at the test data.

**Comment by paulmueller** [comment]
I would like to get rid of the `cv2` dependence in dclab, because `cv2` is not on pypi and it makes testing very painful. If you have the time, please check if we could use scipy/numpy. Otherwise I will have a look.

**Comment by maikherbig** [comment]
The following implementation uses pillow (version 4.1.1) and is much faster :)

import numpy as np
from PIL import Image, ImageDraw

def get_brightness_pillow(images,cont):
    """
    Calculate the mean and std of the grayscale values inside the contour
    
    Parameters
    ----------
    cont: ndarray or list of ndarrays of shape (N,2)
        A 2D array that holds the contour of an event (in pixels)
        e.g. obtained using `mm.contour` where  `mm` is an instance
        of `RTDCBase`. The first and second columns of `cont`
        correspond to the x- and y-coordinates of the contour.
    images: ndarray or list of ndarrays 
        A 2D array that holds the image in form of grayscale values of an event    

    Returns
    -------
    brightn: float or ndarray
        mean brightness in the contour
    brightn_std: float or ndarray
        standard deviation of the grayscale values in the contour
    
    """
    if not type(cont)==list:
        cont = [cont]
    if not type(images)==list:
        images = [images]
    
    msg = 'Nr. of images and contours is not equal'
    assert len(images) == len(cont),msg
    
    #convert contours to PIL polygon format
    cont = [a.ravel().tolist() for a in cont]
    #build a mask / binary image from the contour

    # results are stored in a separate array initialized with nans
    brightn = np.zeros(len(images), dtype=float)*np.nan
    brightn_std = np.zeros(len(images), dtype=float)*np.nan

    for i in range(len(images)):
        frameMask_i = Image.new('L', images[1].shape[::-1], 0)
        ImageDraw.Draw(frameMask_i).polygon(cont[i], outline=1, fill=1)
        frameMask_i = np.array(frameMask_i)
        ind = np.where(frameMask_i==1)
        Mean = np.mean(images[i][ind])           
        Std = np.std(images[i][ind])                              
        brightn[i] = Mean
        brightn_std[i] = Std
                   
    if not type(cont)==list:
        # Do not return a list if the input contour was not in a list
        brightn = brightn[0]
        brightn_std = brightn_std[0]
     
    return(brightn,brightn_std)

**Comment by paulmueller** [comment]
Thanks, while pillow is definitely a better choice than opencv, wouldn't this also work with scipy? Since dclab already uses scipy, I wouldn't want to add another dependency.

https://docs.scipy.org/doc/scipy-0.16.0/reference/generated/scipy.ndimage.morphology.binary_fill_holes.html

**Comment by maikherbig** [comment]
Maybe Pillow has to be added anyway if since imageio depends on it:
"Imageio depends on Numpy and Pillow": http://imageio.readthedocs.io/en/latest/installation.html

**Comment by paulmueller** [comment]
You are right. I still would like to use scipy, if possible. I am not saying that pillow is bad, I just have a better feeling with a scientific library. I will look into it.

**Comment by paulmueller** [comment]
@maikherbig I get the same results for `get_brightness_pillow` and `get_brightness_scipy`, both of which are about 0.5 grayscale values off the accurate average values from the dataset you uploaded. The mean  values computed with opencv are completely off (by a factor >1.5). Which version of opencv are you using?

**Comment by maikherbig** [comment]
I have the opencv version 3.2.0. I get with OpenCV, Pillow and Scipy the same B and B_Std values which are around 61 and 11, respectively (so quite close to the values you got) and match the values in the tdms file. 
The differences between the calculated B values and the B values in the tdms are identical for SciPy, Pillow and OpenCV and go from -3.8053245390301527e-06 to 3.7933861136707492e-06.
I attach another script containing getdata which loads contour avi and tdms of the testdataset and all three get_brightness functions.
[brightness_5.zip](https://github.com/ZELLMECHANIK-DRESDEN/dclab/files/1135943/brightness_5.zip)

**Comment by paulmueller** [comment]
Thanks for your input. I figured out my problem: To get a smaller file size for testing I re-encoded the avi file you provided, which resulted in the offset. With the original video data, the accuracy is below 1e-5. Thanks!

**Comment by paulmueller** [comment]
see https://github.com/ZELLMECHANIK-DRESDEN/dclab/blob/master/dclab/brightness.py

**Pull request closed without merging**
